// electron
export const WILL_CLICK = 'WILL_CLICK';
export const CLICK_LOGIN = 'CLICK_LOGIN';
export const SET_BROWSER_WINDOW = 'SET_BROWSER_WINDOW';
export const SET_BROWSER_VIEW_READY = 'SET_BROWSER_VIEW_READY';
export const SET_BROWSER_VIEW_URL = 'SET_BROWSER_VIEW_URL';
export const ELECTRON_ROUTING = 'ELECTRON_ROUTING';
export const INTERNAL_ADD_BROWSER_VIEW = 'INTERNAL_ADD_BROWSER_VIEW';
export const HIDE_CONFIGURATION = 'HIDE_CONFIGURATION';
export const SHOW_CONFIGURATION = 'SHOW_CONFIGURATION';
export const PERFORM_SCROLL = 'PERFORM_SCROLL';

// configuration
export const SET_CONFIGURATION = 'SET_CONFIGURATION';
export const RESET_CONFIGURATION = 'RESET_CONFIGURATION';
export const NEXT_STAGE = 'NEXT_STAGE';
export const PREVIOUS_STAGE = 'PREVIOUS_STAGE';
export const TOGGLE_ZIP_CODE = 'TOGGLE_ZIP_CODE';

// overlay
export const CLICK_ANIMATION_SHOW = 'CLICK_ANIMATION_SHOW';
export const CLICK_ANIMATION_CLEAR = 'CLICK_ANIMATION_SHOW';
export const CALCULATE_OVERVIEW_BOUNDARIES = 'CALCULATE_OVERVIEW_BOUNDARIES';
export const SET_OVERVIEW_BOUNDARIES = 'SET_OVERVIEW_BOUNDARIES';

// data
export const DATA_OVERVIEW_SET = 'DATA_OVERVIEW_SET';
export const SET_VERDICT = 'SET_VERDICT';
export const REFRESH_VERDICTS = 'REFRESH_VERDICTS';
