// electron
export const WILL_CLICK = 'WILL_CLICK';
export const CLICK_LOGIN = 'CLICK_LOGIN';
export const SET_BROWSER_WINDOW = 'SET_BROWSER_WINDOW';
export const SET_BROWSER_VIEW_READY = 'SET_BROWSER_VIEW_READY';
export const SET_BROWSER_VIEW_URL = 'SET_BROWSER_VIEW_URL';
export const ELECTRON_ROUTING = 'ELECTRON_ROUTING';
export const RETURN_TO_SEARCH_PAGE = 'RETURN_TO_SEARCH_PAGE';
export const INTERNAL_ADD_BROWSER_VIEW = 'INTERNAL_ADD_BROWSER_VIEW';
export const HIDE_CONFIGURATION = 'HIDE_CONFIGURATION';
export const SHOW_CONFIGURATION = 'SHOW_CONFIGURATION';
export const PERFORM_SCROLL = 'PERFORM_SCROLL';
export const NAVIGATE_TO_FLAT_PAGE = 'NAVIGATE_TO_FLAT_PAGE';
export const SET_BOT_IS_ACTING = 'SET_BOT_IS_ACTING';
export const GENERATE_APPLICATION_TEXT_AND_SUBMIT =
  'GENERATE_APPLICATION_TEXT_AND_SUBMIT';
export const SHOW_DEV_TOOLS = 'SHOW_DEV_TOOLS';

// configuration
export const SET_CONFIGURATION = 'SET_CONFIGURATION';
export const RESET_CONFIGURATION = 'RESET_CONFIGURATION';
export const NEXT_STAGE = 'NEXT_STAGE';
export const PREVIOUS_STAGE = 'PREVIOUS_STAGE';
export const SET_SEARCH_URL = 'SET_SEARCH_URL';
export const TOGGLE_POSTCODE = 'TOGGLE_POSTCODE';
export const RESET_POSTCODES = 'RESET_POSTCODES';
export const TOGGLE_FLOOR = 'TOGGLE_FLOOR';
export const TOGGLE_BOOLEAN = 'TOGGLE_BOOLEAN';
export const SET_NUMBER = 'SET_NUMBER';
export const SET_STRING = 'SET_STRING';

// overlay
export const CLICK_ANIMATION_SHOW = 'CLICK_ANIMATION_SHOW';
export const CLICK_ANIMATION_CLEAR = 'CLICK_ANIMATION_SHOW';
export const CALCULATE_OVERVIEW_BOUNDARIES = 'CALCULATE_OVERVIEW_BOUNDARIES';
export const SET_OVERVIEW_BOUNDARIES = 'SET_OVERVIEW_BOUNDARIES';

// data
export const SET_OVERVIEW_DATA = 'SET_OVERVIEW_DATA';
export const SET_FLAT_DATA = 'SET_FLAT_DATA';
export const SET_VERDICT = 'SET_VERDICT';
export const REFRESH_VERDICTS = 'REFRESH_VERDICTS';

// bot
export const INVESTIGATE_FLAT = 'INVESTIGATE_FLAT';
export const RETURN_TO_OVERVIEW = 'RETURN_TO_OVERVIEW';
export const APPLY_TO_FLAT = 'APPLY_TO_FLAT';
export const DISCARD_FLAT = 'DISCARD_FLAT';

// cache
export const SET_CACHE = 'SET_CACHE';
export const RESET_CACHE = 'RESET_CACHE';
export const MARK_COMPLETED = 'MARK_COMPLETED';
